### ISSUE TITLE
deploy checklist

### ISSUE THREAD

**Issue by ismay** [ismay/ismaywolff.nl#14]
- [x] Only use absolute https urls
- [x] Use links without extensions
- [x] Allow crawling of content in robots.txt
- [x] configure analytics and google webmaster tools
- [x] Test with webpagetest.org and google pagespeed
