### ISSUE TITLE
Minor design updates

### ISSUE THREAD

**Issue by ismay** [ismay/ismaywolff.nl#547]
- [x] remove pages from contentful
- [x] remove height and width from placeholder, just use ratio (#550)
- [x] remove markdown, just use summary (#551)
- [x] add other social networks as icons? ([flickr](https://www.flickr.com/photos/ismaywolff), instagram)
- [x] add optional links at bottom of workdetail for article, download, support, etc.
- [x] add zoom button to gallery images (#553)
- [ ] update about and root text
