### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by ismay** [ismay/ismaywolff.nl#584]
- [x] Lazy load offscreen images (#586)
- [x] Update raven (#588)
- [x] Add html lang attribute (#589)
- [x] Inline critical css (global styles and normalize.css) (#592, #594)
- [x] Update manifest's short name (maybe change manifest name back as well)
- [x] Make progressive webapp (#596, #597)

**Comment by ismay** [comment]
Offline implementation:

- [ ] Cache the correct html. The html isn't the same for every route because of ssr. Why does the cached html in the tests not contain the correct preloadedState, when the home scene should have that?
- [ ] Store lastUpdated and refresh app and store every hour. (Use lastUpdated instead of didFetch)
- [ ] Check how it will cope with outdated data. Both in the app code and in the persisted store.
- [ ] Check previously merged offline implementation (and entire implementation)
